### ISSUE TITLE
Change overflow badge theme

### ISSUE THREAD

**Issue by FedericoQuarin** [FlowingCode/BadgeList#3]
As a developer, is it posible to have a feature to change overflow-badge theme from the server side? I would like being able to change it in a similar way like the other badges.

![image](https://github.com/FlowingCode/BadgeList/assets/54511211/14f32fec-b6ba-4219-8611-1ab26cdc899d)

**Comment by paodb** [comment]
Hi, please take a look at the third example here https://addonsv24-staging.flowingcode.com/badge-list/styled, It adds "success" variant to each normal badge and then it adds the same variant to the overflow badge by setting a theme to the badge list:

```
BadgeList badgeList3 = new BadgeList(badges3);
badgeList3.addThemeName("success");
```
