### ISSUE TITLE
Reorder / remove columns in demo

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/BadgeList#8]
When I navigate to the demo, the "roles" column that actually contains the badges is not visible because there are too many columns to the left. As a consequence, the feature remains hidden.

![image](https://github.com/FlowingCode/BadgeList/assets/11554739/7cf362f0-9162-4298-bc30-f2850046fe0a)

**Comment by paodb** [comment]
Discussed with Javier, I will move the Roles column after Last Name one.
